# Generated by Django 5.1.3 on 2024-11-28 21:00

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembresiaTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.IntegerField()),
                ('unidad_tiempo', models.CharField(choices=[('D', 'Días'), ('S', 'Semanas'), ('M', 'Meses'), ('A', 'Años')], default='M', max_length=1)),
                ('beneficios', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10)),
                ('numero_contacto', models.CharField(max_length=15)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='miembros_fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.datetime(2024, 11, 28, 21, 0, 7, 269588, tzinfo=datetime.timezone.utc))),
                ('fecha_final', models.DateField(blank=True, editable=False, null=True)),
                ('tipo_membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Miembros.membresiatipo')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Miembros.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Miembros.miembro')),
            ],
        ),
    ]
