# Generated by Django 5.1.3 on 2024-12-06 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miembros', '0002_alter_membresia_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 15, 56, 39, 740095, tzinfo=datetime.timezone.utc)),
        ),
    ]
