# Generated by Django 5.1.3 on 2024-12-06 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miembros', '0003_membresia_activo_alter_membresia_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membresia',
            name='activo',
        ),
        migrations.AddField(
            model_name='membresiatipo',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 16, 13, 38, 715322, tzinfo=datetime.timezone.utc)),
        ),
    ]
