# Generated by Django 5.1.3 on 2024-12-06 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miembros', '0004_remove_membresia_activo_membresiatipo_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 16, 13, 52, 788109, tzinfo=datetime.timezone.utc)),
        ),
    ]
