# Generated by Django 5.1.3 on 2024-12-08 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miembros', '0005_alter_membresia_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2024, 12, 8, 14, 28, 28, 746670, tzinfo=datetime.timezone.utc)),
        ),
    ]
