# Generated by Django 5.1.3 on 2024-12-13 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miembros', '0008_alter_membresia_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2024, 12, 13, 2, 10, 38, 790857, tzinfo=datetime.timezone.utc)),
        ),
    ]
