# Generated by Django 5.1.3 on 2024-12-13 02:38

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miembros', '0009_alter_membresia_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='foto_cloud',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2024, 12, 13, 2, 38, 51, 535788, tzinfo=datetime.timezone.utc)),
        ),
    ]
