# Generated by Django 5.1.3 on 2024-12-14 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miembros', '0013_alter_membresia_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2024, 12, 14, 20, 54, 54, 869556, tzinfo=datetime.timezone.utc)),
        ),
    ]
