# Generated by Django 5.1.3 on 2024-11-28 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aparato',
            fields=[
                ('idAparatos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=80)),
                ('cantidad', models.IntegerField()),
                ('bandera', models.BooleanField()),
                ('tipo', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaAparato',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaApa_Aparato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAparato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aparatos.aparato')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aparatos.categoriaaparato')),
            ],
        ),
    ]
